version: '3'

services:
  status-mirror:
    build: .
    ports:
      - "3000:3000"
    environment:
      - SOURCE_STATUS_URL=https://status.ciii.club/status/codex
      - CACHE_TTL=60
      - SITE_TITLE=Ciii-codex Status
    restart: always
    container_name: status-mirror
